# Generated by Django 4.1 on 2024-03-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'MOTORCYCLE'), ('TRUCK', 'TRUCK'), ('SAILBOAT', 'SAILBOAT'), ('BOAT', 'BOAT')], default='CAR', max_length=25)),
                ('owner_id', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
                ('patent', models.CharField(max_length=7)),
                ('insurance', models.CharField(max_length=7)),
                ('expiration_date', models.DateField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(null=True)),
                ('is_gone', models.BooleanField(default=False)),
            ],
        ),
    ]
