# Generated by Django 4.1 on 2024-03-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_private_area_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_gone',
            new_name='is_deleted',
        ),
    ]
