CAR = "CAR"
MOTORCYCLE = "MOTORCYCLE"
TRUCK = "TRUCK"
SAILBOAT = "SAILBOAT"
BOAT = "BOAT"

VEHICLE_TYPES_CHOISES_DICT = {
    "CAR": "Car",
    "MOTORCYCLE": "MOTORCYCLE",
    "TRUCK": "TRUCK",
    "SAILBOAT": "SAILBOAT",
    "BOAT": "BOAT",    
}

VEHICLE_TYPES_CHOISES = (
    (CAR, "Car"),
    (MOTORCYCLE, "MOTORCYCLE"),
    (TRUCK, "TRUCK"),
    (SAILBOAT, "SAILBOAT"),
    (BOAT, "BOAT"),
)