# Generated by Django 4.1 on 2024-03-15 01:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_vehicles_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'MOTORCYCLE'), ('TRUCK', 'TRUCK'), ('SAILBOAT', 'SAILBOAT'), ('BOAT', 'BOAT')], default='CAR', max_length=25), size=None)),
                ('city', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
